# Generated by Django 6.0 on 2025-12-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_customstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('analyst_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upside_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('forward_pe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verdict', models.CharField(default='Neutral', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
