# Generated by Django 6.0 on 2025-12-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stockanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockanalysis',
            name='analyst_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consensus 12-Month Price Target', max_digits=10, null=True),
        ),
    ]
