# Generated by Django 6.0 on 2025-12-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stockscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockscore',
            options={'verbose_name': 'Stock Forecast', 'verbose_name_plural': 'Stock Forecasts (12 Mo)'},
        ),
        migrations.AlterField(
            model_name='stockscore',
            name='score',
            field=models.IntegerField(help_text='AI prediction of performance over the next 12 months (0-100)', verbose_name='12-Mo Target Score'),
        ),
    ]
