# Generated by Django 6.0 on 2025-12-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_stockscore_options_alter_stockscore_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockscore',
            options={'verbose_name': 'Stock Forecast', 'verbose_name_plural': 'Stock Forecasts Score(12 Mo)'},
        ),
    ]
