# Generated by Django 6.0 on 2026-01-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_stockscore_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='history_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='period_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='period_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='period_years',
            field=models.IntegerField(blank=True, help_text='Number of years used for high/low calc', null=True),
        ),
    ]
