# Generated by Django 6.0 on 2026-01-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_stockanalysis_history_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(help_text='Test Set Accuracy')),
                ('precision', models.FloatField(help_text='Test Set Precision (The most important metric)')),
                ('oob_accuracy', models.FloatField(blank=True, help_text='Out-of-Bag Score from final model', null=True)),
                ('data_points', models.IntegerField(help_text='How many total rows of data we learned from')),
            ],
        ),
    ]
