# Generated by Django 6.0 on 2026-01-08 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_aimodellog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodellog',
            name='data_points',
            field=models.IntegerField(help_text='Total rows of data used'),
        ),
        migrations.AlterField(
            model_name='aimodellog',
            name='oob_accuracy',
            field=models.FloatField(blank=True, help_text='Out-of-Bag Score', null=True),
        ),
        migrations.AlterField(
            model_name='aimodellog',
            name='precision',
            field=models.FloatField(help_text='Test Set Precision (Win Rate)'),
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('date', models.DateField(null=True)),
                ('prob_score', models.FloatField(help_text='AI Confidence score (0-100)')),
                ('prediction', models.IntegerField(help_text='1=Buy, 0=Wait')),
                ('actual_target', models.IntegerField(help_text='1=Up, 0=Down')),
                ('correct', models.BooleanField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='stocks.aimodellog')),
            ],
        ),
    ]
