# Generated by Django 6.0 on 2026-01-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_alter_aimodellog_data_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestresult',
            name='correct',
            field=models.IntegerField(help_text='1=Correct, 0=Wrong'),
        ),
    ]
