# Generated by Django 6.0 on 2026-01-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_alter_backtestresult_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockscore',
            name='trustworthy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockscore',
            name='untrustworthy_count',
            field=models.IntegerField(default=0),
        ),
    ]
