# Generated by Django 6.0 on 2026-01-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_stockscore_trustworthy_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='analyst_target_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='analyst_target_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
