# Generated by Django 6.0 on 2026-01-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_stockanalysis_analyst_target_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='analyst_rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='current_target',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='previous_target',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='price_action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
