# Generated by Django 6.0 on 2026-02-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_stockanalysis_analyst_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='expected_target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='p1',
            field=models.FloatField(blank=True, help_text='Worst Case Prob', null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='p2',
            field=models.FloatField(blank=True, help_text='Base Case Prob', null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='p3',
            field=models.FloatField(blank=True, help_text='Best Case Prob', null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='price1',
            field=models.FloatField(blank=True, help_text='Worst Case Impact %', null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='price2',
            field=models.FloatField(blank=True, help_text='Base Case Impact %', null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='price3',
            field=models.FloatField(blank=True, help_text='Best Case Impact %', null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='top_ai_driver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
