# Generated by Django 6.0 on 2026-02-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_stockanalysis_expected_target_price_stockanalysis_p1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='kelly_accuracy_score',
            field=models.FloatField(blank=True, help_text='AI Model R-Squared Score (0-100%)', null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='kelly_avg_error_margin',
            field=models.FloatField(blank=True, help_text='Average percentage error in past predictions', null=True),
        ),
    ]
