# Generated by Django 6.0 on 2026-02-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_stockanalysis_kelly_accuracy_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='backtest_sample_count',
            field=models.IntegerField(blank=True, help_text='Number of historical years used for training', null=True),
        ),
    ]
