# Generated by Django 6.0 on 2026-02-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_stockanalysis_backtest_sample_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockanalysis',
            name='expected_target_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kelley Expect Price (P1, P2, P3 weighted calculation', max_digits=10, null=True, verbose_name='Kelley Expected Price'),
        ),
    ]
