# Generated by Django 6.0 on 2026-03-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_alter_stockanalysis_expected_target_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockscore',
            name='buy_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockscore',
            name='sell_score',
            field=models.IntegerField(default=0),
        ),
    ]
