# Generated by Django 6.0 on 2026-03-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_stockscore_buy_score_stockscore_sell_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodellog',
            name='f1_score',
            field=models.FloatField(default=0.0, help_text='Test Set F1-Score'),
        ),
        migrations.AddField(
            model_name='aimodellog',
            name='recall',
            field=models.FloatField(default=0.0, help_text='Test Set Recall'),
        ),
        migrations.AddField(
            model_name='aimodellog',
            name='roc_auc',
            field=models.FloatField(default=0.0, help_text='Test Set ROC-AUC Score'),
        ),
    ]
