# Generated by Django 6.0 on 2026-03-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_aimodellog_f1_score_aimodellog_recall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='analysis_note_compound',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='compound_profit_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='period_low_compound',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='period_years_compound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='projected_price_by_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
